name: test_task
description: "A new Flutter test"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
